### ISSUE TITLE
Segfault PHP sur la testapp

### ISSUE THREAD

**Issue by brice-t** [jelix/jelix#144]
Ce n'est pas un bug de Jelix, mais ça fait un moment que je cherche, alors je partage ... ;)

J'ai réinstallé la testapp (master) et essayé de faire tourner les tests. J'obtiens un plantage (segfault) systématique de php. J'ai isolé le fait que jdao.factory_base.html_cli.php (au moins) provoque ce plantage. Plus précisément, si je ne conserve que sa méthode testFindAll(), le fait que cette méthode appelle ou non findAll() provoque ou non le crash. D'autre part, quelques tests m'ont montré que ça semble lié à l'utilisation de Mock de simpletest.

Mais ce crash survient, si je comprends ce que me dis gdb, à la fin de l'exécution du script PHP (à la destruction des objets). J'ai trouvé notamment https://bugs.php.net/bug.php?id=64111 qui semble lié à ce problème.

Je n'ai pas de workaround pour le moment.

Ma conf :
Ubuntu 13.04 en x86_64 / apache2 2.2.22-6ubuntu5 / php5 5.4.9-4ubuntu2.1
(laurentj a une conf a priori similaire mais pas de problème ...)

**Comment by laurentj** [comment]
Plus de tests simpletest dans  Jelix 1.7-pre. Plus de problèmes de crash de mon coté
