### ISSUE TITLE
form with datepicker inside html_fragment not displayed correctly

### ISSUE THREAD

**Issue by qix67** [jelix/jelix#163]
Hello,

There is a problem when a form with datepicker is displayed inside html_fragment. The first time, the datepicker icon is displayed but if the fragment is loaded a second time, no icon is added. The problem occurs in jelix 1.4.0 but the file seems to be the same in all later versions.

The problem occurs because during jelix_datepicker_default call, the first time, files required by init.js are not already loaded and document ready function of init.js is called after jFormsJQ.tForm.addControl.
On the second fragment loading, document ready function fires immediately because extraneous files are already loaded but because jFormsJQ.tForm.addControl was not yet called, formname of the control is missing. Moreover, on the second call, the array of datepickered control was not flushed then each field is tagged with 2 datepicker icons (1 per html_fragment load).

I enclose to this post an unminified fixed init.js (lib/jelix-www/js/jforms/datepickers/default/). It is not an image, just a .js with a png extension.

![init js fake_png](https://cloud.githubusercontent.com/assets/4102181/2983701/5f418f4a-dc28-11e3-9a96-2391a22d7c4f.png)

Thanks,

**Comment by laurentj** [comment]
Loading of forms with an html fragment has been fixed by commit 08569e6f7849c271e8f74d4fef131581d9b3605f.

However, it seems it does not fix completely your issue about icons. I will fix that.
