### ISSUE TITLE
Modifications de mainconfig.ini.php toujours ignorées au profit de la version mise en cache

### ISSUE THREAD

**Issue by qix67** [jelix/jelix#196]
Bonjour,

j'ai récemment mis à jour mon jelix de la version 1.4.0 à la 1.6.2 et depuis, j'ai remarqué que les changements réalisés sur mainconfig.ini.php n'étaient plus pris en compte jusqu'à ce que le répertoire temp de l'application soit purgé.

après un peu de débugage, j'ai trouvé que le problème venait du fichier jConfig.class.php, méthode load. Dans celle-ci, la variable $dc est mal initialisée par la ligne:
   $dc = jApp::configPath(jApp::mainConfigFile());

Le problème est qu'au lieu d'obtenir /XXX/var/config/mainconfig.ini.php, il contient /XXX/var/config//XXX/var/config/mainconfig.ini.php. Ceci tient au fait que jApp::mainConfigFile appelle déjà jApp::configPath en interne.

Il faut donc remplacer la ligne par
   $dc = jApp::mainConfigFile();

Cordialement,

**Comment by laurentj** [comment]
Merci pour le diagnostic. c'est corrigé :-)
