### ISSUE TITLE
Auto-increment fields with sequences do not work with the OCI DAO builder

### ISSUE THREAD

**Issue by benoit-l** [jelix/jelix#197]
It seems impossible to use autoincrements with sequences in Oracle as from Jelix 1.6.0. The PDO-based driver used in Jelix 1.5 didn't have this problem.

There is a buildInsertMethod function in oci.daobuilder.php where autoincrement fields are explicitely forbidden, advising to use a sequence instead (which makes sense):
https://github.com/jelix/jelix/blob/master/lib/jelix-legacy/plugins/db/oci/oci.daobuilder.php#L78

But that test is always true with jDAO because when a field is declared with a sequence, it is automatically assumed autoincrement as well:
https://github.com/jelix/jelix/blob/master/lib/jelix-legacy/dao/jDaoProperty.class.php#L161

Even if the first test passed, it also looks like the builder would generate incorrect code by closing the insert function block too early in the case an auto-increment PK is found:
https://github.com/jelix/jelix/blob/master/lib/jelix-legacy/plugins/db/oci/oci.daobuilder.php#L157

**Comment by laurentj** [comment]
thank you for your report. I hope I fixed bugs (I don't have Oracle to test it). Please tell me if it is ok for you. see [latest builds](http://download.jelix.org/jelix/nightly/1.6.x/)
