### ISSUE TITLE
Update PHPMailer library to support newer PHP versions

### ISSUE THREAD

**Issue by xv4y** [jelix/jelix#211]
Hi,

PHP 5.5 is complaining with E_DEPRECATED errors that the current PHPMailer version shipped with Jelix 1.6.3 is using the /e modifier in preg_replace(), preg_replace_callback should be used instead.

No hurry but we don't until when PHP will support this obsolete modifier.

Regards,
Yan.

**Comment by laurentj** [comment]
Newer PHPMailer is included (as a Composer package) in the upcoming Jelix 1.7, but we should also update Jelix 1.6
