### ISSUE TITLE
Error when using classes in sub-directories, as datasource in jForms files

### ISSUE THREAD

**Issue by Orabee** [jelix/jelix#221]
When I put classes in sub-directories of the classes/ directory, this doesn't work :
<datasource class="my_class~my_folder/product" />

**Comment by laurentj** [comment]
It seems an example of what it doesn't work, is missing. Please explain what does not work

**Comment by Orabee** [comment]
Le paragraphe http://docs.jelix.org/fr/manuel-1.4/utilisation-classes#instanciation-d-une-classe-avec-jclasses, nous indique la possibilité de "ranger" une classe dans un sous dossier qu'on aura préalablement créé.
Je m'explique, je crée la classe stockservice.class.php, et je souhaite la mettre dans /module/mon_module/classes/stocks/stockservice.class.php (J'ai repris l'exemple de la doc).

Jusque là, tout va bien. En faisant appel à getService(), cela fonctionne parfaitement. On se dit alors qu'il est peut-être possible de faire la même chose avec les formulaires. Par exemple, dans le fichier stock.form.xml, lorsque je place le code suivant :
<menulist ref="stock">
        <label locale="mon_module~form.stock"/>
        <datasource class="mon_module~stocks/stockservice" />
</menulist>

Cela ne marche pas et j'obtiens une erreur.

**Comment by julieni** [comment]
Hello, works for me in jelix 1.6

```xml
<menulist ref="category" required="true">
    <label>Category</label>
    <datasource class="catalog~jForms/jFormsDatasourceCategories"/>
</menulist>
```

@Orabee : can you confirm your class implements jIFormsDatasource, jIFormsDatasource2 or the recently added jIFormsDynamicDatasource ? Which error message do you have ?

```php
<?php
class jFormsDatasourceCategories implements jIFormsDatasource2{
//...
```

**Comment by laurentj** [comment]
I added an exemple in testapp of Jelix 1.6.x, and it works well. I cannot reproduced the issue. Since Jelix 1.4, there are no significant change on the code responsible of the class loading, I don't think there is this issue in Jelix 1.4. Anyway, jelix 1.4 is not maintained anymore since few months. I won't fix anything Jelix 1.4.

If you use jelix 1.4, please migrate to 1.6.
