### ISSUE TITLE
Retrocompatibility broken for jForms < 1.5

### ISSUE THREAD

**Issue by migratis** [jelix/jelix#229]
Several point are broken to keep the compatibility of jForms developped under versions of Jelix inferior to 1.5 :

1 - abstract public function outputControlValue($ctrl, $attributes=array()) not exists in lib\jelix\forms\legacy\jFormsBuilderBase.class.php

2 - public function outputControlValue($ctrl, $attributes=array()) not implemented in lib\jelix\forms\legacy\jFormsBuilderHtml.class.php

3 - The HTML attributes (class) are no longer added in the form tag

**Comment by migratis** [comment]
I have resolved the point 3 by implementing the method setOptions into my custom form builder plugin.

**Comment by laurentj** [comment]
New methods have been added.

For the HTML attributes, I don't see why there is an issue. Theorically, it is supported. The setOptions method is already implemented into jFormsBuilderBase.

**Comment by migratis** [comment]
Thanks Laurent, yes it is not an issue for Jelix, I have missed to implement the setOptions Method in my custom jForm plugin.
