### ISSUE TITLE
jDb: Autocommit and PostgreSQL 9.5

### ISSUE THREAD

**Issue by xv4y** [jelix/jelix#234]
Since PostgreSQL 9.1 AUTOCOMMIT in PostgreSQL was depreciated. The "SET AUTOCOMMIT" command was just silently ignored.
Starting with PostgreSQL 9.5, issuing this command gives an error and hence Jelix does not work with PostgreSQL 9.5

The solution is to comment out the setAutoCommit lines in the pgsqlDbConnection.php constructor.

Yannick.

**Comment by laurentj** [comment]
@xv4y well, setAutocommit() call _autoCommitNotify() which executes "SET AUTOCOMMIT" only if the version of postgresql is lower than 7.4. At least in Jelix 1.6.

Which version of Jelix do you use?

**Comment by xv4y** [comment]
Hi Laurent,

At that time that was Jelix 1.6.4.
However I forgot that I used my own DB plugin which is fork of the Jelix one. Maybe it was "out of sync" regarding this.
It was calling _autoCommitNotify() but I don't think PgSQL version was checked.
I will have a closer look at it and keep you informed.
Sorry if I was mistaken.

Yannick.

**Comment by xv4y** [comment]
Hi Laurent,

Sorry for being late in answering but I'm busy as I will soon move to another country.

I confirm that this issue was on my own modified version of the plugin driver (a version that allows asynchronous/concurrent queries).
The version included in Jelix 1.6.4 (and 1.6.5) works great regarding that matter.

I apologize for the mistake.

Regards,
Yan.
---
Yannick DEVOS - XV4Y
http://www.qscope.org/
http://xv4y.radioclub.asia/
