### ISSUE TITLE
Improving cookie security for XSS in jAuth

### ISSUE THREAD

**Issue by xv4y** [jelix/jelix#237]
Hi,

This is not a bug, just a suggestion for improvement.
While doing Vulnerability Assessment with OpenVAS on my servers, I found that the cookies set by jAuth are considered "unsecured". The security risk is low, but as it is now, the cookie can be used by JavaScript (by example) while they should be available only through HTTP.
See OWASP page about it for more details :
https://www.owasp.org/index.php/HttpOnly

The modification is easy and concerns only /lib/jelix/auth/jAuth.class.php.
When using the PHP function setcookie(), the last parameter has to be set to "true". Please see PHP manual for more details.
http://php.net/manual/en/function.setcookie.php

Thanks,
Yan.

**Comment by laurentj** [comment]
Thank you for your report!
