### ISSUE TITLE
soap response  not configured in Jelix 1.6

### ISSUE THREAD

**Issue by migratis** [jelix/jelix#242]
The entries soap=jResponseSoap in the sections [responses] and [_coreResponses] of the file lib/jelix/core/defaultconfig.ini.php is no longer present.
To make things working without modifying the Jelix lib is to add it in mainconfig.ini.php of the App.
Does this is a bug or a feature to add in the documentation ?

**Comment by laurentj** [comment]
You should activate the jsoap modules (php cmd.php installmodule jsoap). Its installer does expected modifications in your configuration. All about SOAP have been migrated in this module since Jelix 1.5.

**Comment by laurentj** [comment]
Is it ok for you?

**Comment by migratis** [comment]
Yes it is ok, sorry for the delay to answer... So I did not red the documentation carefully ?

**Comment by laurentj** [comment]
[The documentation seems ok about this subject](http://docs.jelix.org/en/manual-1.6/web-services/soap) and there were [migration instructions about SOAP](http://docs.jelix.org/en/manual-1.5/installation/migrate#soap-support). So you missed them ;-)

Always read releases note and migration instructions each time you update a lib ;-)

**Comment by migratis** [comment]
Salut Laurent,

Voici mes fichiers de conf de base et compilés, concernant la 
compilation qui ne reprend pas les infos de defaultconfig.ini.php pour 
un autre entrypoint que index.php (ici exemple admin.php, le 
config.ini.php est celui d'admin.
Je te rappelle que je suis en 1.5.6 mais que ce problème existe depuis 
le passage en 1.2.13.
Je pensais qu'il allait se régler en upgradant.

Merci d'avance !

Philippe
;<?php die(''); ?>
;for security reasons , don't remove or modify the first line

startModule=cms
startAction="default:index"

modulesPath="lib:jelix-modules/,app:modules/,lib:shared-modules/"

[coordplugins]
;nom = file_ini_name or 1
cms = cms.coord.ini.php
auth = auth.coord.ini.php
jacl2 = jacl2.coord.ini.php

[responses]
html = cmsHtmlResponse
content_html = cmsContentHtmlResponse
inner_content_html = cmsInnerContentHtmlResponse

[sessions]
loadClasses = ""

[acl2]
; example of driver: "db"
driver = db




;<?php die(''); ?>
; for security reasons , don't remove or modify the first line
; don't modify this file if you don't know what you do. it is generated automatically by jInstaller


[index]
jelix.installed=1
jelix.version=1.5.6
jacl2db.installed=1
jacl2db.version=1.2
jacldb.installed=0
jacldb.version=
jauth.installed=1
jauth.version=1.2
jauthdb.installed=1
jauthdb.version=1.2
junittests.installed=1
junittests.version=1.2
jWSDL.installed=1
jWSDL.version=1.2
cms.installed=1
cms.version=0.1pre
site.installed=1
site.version=0.1pre
bv.installed=1
bv.version=1.0
jelix.version.date="2015-10-26 22:03"
jacl2db.version.date=2010-12-03
jauth.version.date=2010-12-03
jauthdb.version.date=2010-12-03
junittests.version.date=2010-12-03
jWSDL.version.date=2010-12-03
cms.version.date=
site.version.date=
bv.version.date=2016-06-10


jacl.installed=0
jacl.version=
jacl2.installed=1
jacl2.version=1.5
jpref.installed=0
jpref.version=
jsoap.installed=0
jsoap.version=
jacl2.version.date=2012-09-18
jacl2.firstversion=1.5
jacl2.firstversion.date=2012-09-18
[light]
jelix.installed=0
jelix.version=
jacl2db.installed=0
jacl2db.version=
jacldb.installed=0
jacldb.version=
jauth.installed=0
jauth.version=
jauthdb.installed=0
jauthdb.version=
junittests.installed=0
junittests.version=
jWSDL.installed=0
jWSDL.version=
cms.installed=0
cms.version=
site.installed=0
site.version=
bv.installed=0
bv.version=
jacl.installed=0
jacl.version=
jacl2.installed=0
jacl2.version=
jpref.installed=0
jpref.version=
jsoap.installed=0
jsoap.version=
[jelix]
jelix.installed=0
jelix.version=
jacl2db.installed=0
jacl2db.version=
jacldb.installed=0
jacldb.version=
jauth.installed=0
jauth.version=
jauthdb.installed=0
jauthdb.version=
junittests.installed=0
junittests.version=
jWSDL.installed=0
jWSDL.version=
cms.installed=0
cms.version=
site.installed=0
site.version=
bv.installed=0
bv.version=
jacl.installed=0
jacl.version=
jacl2.installed=0
jacl2.version=
jpref.installed=0
jpref.version=
jsoap.installed=0
jsoap.version=
[admin]
jelix.installed=0
jelix.version=
jacl2db.installed=0
jacl2db.version=
jacldb.installed=0
jacldb.version=
jauth.installed=0
jauth.version=
jauthdb.installed=0
jauthdb.version=
junittests.installed=0
junittests.version=
jWSDL.installed=0
jWSDL.version=
cms.installed=0
cms.version=
site.installed=0
site.version=
bv.installed=0
bv.version=
jacl.installed=0
jacl.version=
jacl2.installed=0
jacl2.version=
jpref.installed=0
jpref.version=
jsoap.installed=0
jsoap.version=
[crud]
jelix.installed=0
jelix.version=
jacl2db.installed=0
jacl2db.version=
jacldb.installed=0
jacldb.version=
jauth.installed=0
jauth.version=
jauthdb.installed=0
jauthdb.version=
junittests.installed=0
junittests.version=
jWSDL.installed=0
jWSDL.version=
cms.installed=0
cms.version=
site.installed=0
site.version=
bv.installed=0
bv.version=
jacl.installed=0
jacl.version=
jacl2.installed=0
jacl2.version=
jpref.installed=0
jpref.version=
jsoap.installed=0
jsoap.version=
[utils]
jelix.installed=0
jelix.version=
jacl2db.installed=0
jacl2db.version=
jacldb.installed=0
jacldb.version=
jauth.installed=0
jauth.version=
jauthdb.installed=0
jauthdb.version=
junittests.installed=0
junittests.version=
jWSDL.installed=0
jWSDL.version=
cms.installed=0
cms.version=
site.installed=0
site.version=
bv.installed=0
bv.version=
jacl.installed=0
jacl.version=
jacl2.installed=0
jacl2.version=
jpref.installed=0
jpref.version=
jsoap.installed=0
jsoap.version=
[soap]
jelix.installed=0
jelix.version=
jacl2db.installed=0
jacl2db.version=
jacldb.installed=0
jacldb.version=
jauth.installed=0
jauth.version=
jauthdb.installed=0
jauthdb.version=
junittests.installed=0
junittests.version=
jWSDL.installed=0
jWSDL.version=
cms.installed=0
cms.version=
site.installed=0
site.version=
bv.installed=0
bv.version=
jacl.installed=0
jacl.version=
jacl2.installed=0
jacl2.version=
jpref.installed=0
jpref.version=
jsoap.installed=0
jsoap.version=
[help]
jelix.installed=1
jelix.version=1.2.13
jacl2db.installed=1
jacl2db.version=1.2
jacldb.installed=0
jacldb.version=
jauth.installed=1
jauth.version=1.2
jauthdb.installed=1
jauthdb.version=1.2
junittests.installed=1
junittests.version=1.2
jWSDL.installed=1
jWSDL.version=1.2
cms.installed=1
cms.version=0.1pre
site.installed=1
site.version=0.1pre
bv.installed=1
bv.version=1.0
jelix.version.date="2013-09-18 23:58"
jelix.firstversion=1.2.13
jelix.firstversion.date="2013-09-18 23:58"
jacl2db.version.date=2010-12-03
jacl2db.firstversion=1.2
jacl2db.firstversion.date=2010-12-03
jauth.version.date=2010-12-03
jauth.firstversion=1.2
jauth.firstversion.date=2010-12-03
jauthdb.version.date=2010-12-03
jauthdb.firstversion=1.2
jauthdb.firstversion.date=2010-12-03
junittests.version.date=2010-12-03
junittests.firstversion=1.2
junittests.firstversion.date=2010-12-03
jWSDL.version.date=2010-12-03
jWSDL.firstversion=1.2
jWSDL.firstversion.date=2010-12-03
cms.version.date=
cms.firstversion=0.1pre
cms.firstversion.date=
site.version.date=
site.firstversion=0.1pre
site.firstversion.date=
bv.version.date=2016-06-10
bv.firstversion=1.0
bv.firstversion.date=2016-06-10
[__modules_data]
jelix.contexts="db:pgJelix"
jacl2db.contexts="jacl2:help/jacl2.coord.ini.php,db:pgJelix"
jauth.contexts="auth:help/auth.coord.ini.php"
jauthdb.contexts="help/auth.coord.ini.php,db:pgJelix"
junittests.contexts=
jWSDL.contexts=

**Comment by laurentj** [comment]
@migratis  j'ai ouvert [une nouvelle issue](https://github.com/jelix/jelix/issues/254)
