### ISSUE TITLE
Version 1.6.8  - Authentification

### ISSUE THREAD

**Issue by dlalleme** [jelix/jelix#261]
Bonjour,

Je suis passé en version 1.6.8 et en m'authentifiant j'ai l'erreur suivante :

`error (609)Les paramètres de configuration suivants doivent être renseignés : persistant_cookie_name, persistant_crypt_key`

Cela ne m'empêche pas de me connecter mais j'ai tout de même cette erreur dans error.log.

J'utilise jcommunity

Cordialement

Denis

**Comment by laurentj** [comment]
Cela a déjà été corrigé dans le commit ae099701feb70d2dcec85fa47dcfe404109577c0
