### ISSUE TITLE
Coord plugin conf file location in jelix 1.7

### ISSUE THREAD

**Issue by sylvain261** [jelix/jelix#274]
In Jelix 1.7 i was expecting that the path of the coord plugin conf file was in the new app folder rather than in the var folder.
in jConfigCompiler.class.php::checkCoordPluginsPath   jApp::configPath might be replaced by  jApp::appConfigPath

**Comment by laurentj** [comment]
Fixed in commit 4653a64c550e5d32f0a89bf686291cc4c1966a15
