### ISSUE TITLE
Major regression in form submission with enctype=multipart/form-data

### ISSUE THREAD

**Issue by laurentj** [jelix/jelix#280]
The regression appears after pr #269. Parameters received with POST method and content-type multipart/form-data are not available anymore. We only have the module and the action parameter.

**Comment by julieni** [comment]
Maybe checks on line https://github.com/jelix/jelix/blob/jelix-1.6.x/lib/jelix/core/request/jClassicRequest.class.php#L29 are too restrictive on content-type. Can content-type be more than multipart/form-data, ie with a charset ?

**Comment by julieni** [comment]
Sh*t, seems that boundary is in the Content-Type header field.... should use strpos instead of strict equality...

**Comment by julieni** [comment]
see #281

**Comment by laurentj** [comment]
I have also a patch too

**Comment by laurentj** [comment]
Fixed by commit #d81e043a44a315a46d7e0567dc2e9135c932de64
