### ISSUE TITLE
Impossible de créer des DAOs à partir de PHP CLI pour le driver PDO sqlsrv

### ISSUE THREAD

**Issue by maelBL** [jelix/jelix#284]
Bonjour,

J'ai tenté de générer des DAOs à l'aide de la commande `php.exe cmd.php createdao xxx yyy zzz` et malheureusement une erreur survient : `[error:408] jDb driver "sqlsrv" is not found`.

Dans l'application en elle-même ça marche bien en faisant une connexion et une requête SELECT, mais dans l'invite de commande PHP il veut juste pas.

Je précise encore que j'ai bien modifié les deux php.ini (celui de Wamp et celui de PHP) en indiquant mes drivers mais rien n'y fait. J'utilise la version "jelix-1.6.13-dev" avec PHP 5.6.25.

Edit :
Après avoir créé un DAO à la main pour tester, je vois que `jDao::get()` retourne la même erreur. Du coup je me demande, serait-il possible que la raison de cette erreur soit que le driver PDO sqlsrv n'est pas supporté par jDao ?

**Comment by maelBL** [comment]
Précision supplémentaire : 
Après avoir créé un DAO à la main pour tester, je vois que `jDao::get()` retourne la même erreur. Du coup je me demande, serait.il possible que la raison de cette erreur soit que le driver PDO sqlsrv n'est pas supporté par jDao ?

**Comment by foxmask** [comment]
It looks like that it's the case like you can see https://github.com/jelix/jelix/tree/master/lib/jelix-legacy/plugins/db

**Comment by maelBL** [comment]
- `$cnx = jDb::getConnection();` --> Fonctionne
- `$fact = jDao::get('news~news');` --> Ne fonctionne pas

Par curiosité, j'ai copié le plugin `/plugins/db/mssql` et remplacé tous les termes "mssql" par "sqlsrv" afin d'en créer un nouveau plugin (sans rien modifier d'autre). Et curieusement, la commande `php.exe cmd.php createdao xxx yyy zzz` est passée cette fois-ci ! Mais dans l'application, `jDao::get('news~news');` ne fonctionne toujours pas.

Alors est-ce qu'en fait les DAO ne fonctionne pas avec PDO ?

**Comment by laurentj** [comment]
Non, il n'y a pas de "builder" de dao pour les connections sqlsrv via PDO. Il faut donc configurer avec le plugin mssql fourni, sans activer pdo dans la config.

```
driver=mssql
host=...
user=...
password=...
```

pas de `usepdo=on` donc...

à noter que dans la 1.7 à venir, les plugins pour le "daobuilder" sont séparés des plugins des bases de données, ce qui permet donc d'utiliser une connection PDO avec le plugin "daobuilder" qui convient.

**Comment by maelBL** [comment]
Merci pour votre réponse ! Je vois. Mais puisque l'extension mssql est considérée comme [deprecated](http://php.net/manual/fr/intro.mssql.php) (elle n'est d'ailleurs plus disponible dans PHP 7), il n'y a en donc aucune solution "fiable" en attendant la 1.7, c'est cela ?

**Comment by laurentj** [comment]
@maelBL je vais essayer de faire un driver pour 1.6.x aujourd'hui. Mais j'aurais besoin de toi pour tester.

**Comment by foxmask** [comment]
@maelbl vous pouvez vous retrouver sur IRC du besoin.

**Comment by maelBL** [comment]
@laurentj Wouah, ce serait le top ! :+1:  Je suis sur le channel IRC jusqu'à 17h environ. J'aide volontiers en cas de besoin et pour tester.

**Comment by laurentj** [comment]
Premier jet du driver sqlsrv. à tester et à corriger, compléter etc...

**Comment by laurentj** [comment]
@maelBL sur irc tu as écris
> lorsque j'exécute la commande "createdaocrud", 
> j'ai plusieurs "notices" qui s'affichent, par exemple : [notice:1] undefined 
> index: varchar; [notice:1] undefined offset: 1; [notice:1] undefined offset: 
> 6

Pourrais-tu donner les messages exactes ? (voir fichier var/log/error.log )

**Comment by maelBL** [comment]
Voilà ce que j'ai. J'en met une seule copie mais il y a ces trois notices pour chaque colonne de la table.

 ```
2017-02-07 16:43:11	::1	notice	2017-02-07 16:43:11	::1	[8]	
Undefined index: varchar	C:\wamp\www\jelix\lib\jelix\db\jDbTools.class.php	159
	/jelix/actu.org/www/index.php/news/news
array (   'module' => 'news',   'action' => 'news:index', )

	0	jDbTools->getTypeInfo()	C:\wamp\www\jelix\lib\jelix\dao\jDaoProperty.class.php : 155
	1	jDaoProperty->__construct()	C:\wamp\www\jelix\lib\jelix\dao\jDaoParser.class.php : 196
	2	jDaoParser->parseRecord()	C:\wamp\www\jelix\lib\jelix\dao\jDaoParser.class.php : 104
	3	jDaoParser->parse()	C:\wamp\www\jelix\lib\jelix\dao\jDaoCompiler.class.php : 51
	4	jDaoCompiler->compile()	C:\wamp\www\jelix\lib\jelix\core\jIncluder.class.php : 113
	5	jIncluder::inc()	C:\wamp\www\jelix\lib\jelix\dao\jDao.class.php : 39
	6	jDao::create()	C:\wamp\www\jelix\lib\jelix\dao\jDao.class.php : 62
	7	jDao::get()	C:\wamp\www\jelix\lib\jelix\controllers\jControllerDaoCrud.class.php : 181
	8	jControllerDaoCrud->index()	C:\wamp\www\jelix\lib\jelix\core\jCoordinator.class.php : 225
	9	jCoordinator->process()	C:\wamp\www\jelix\actu.org\www\index.php : 19


2017-02-07 16:43:11	::1	notice	2017-02-07 16:43:11	::1	[8]	
Undefined offset: 1	C:\wamp\www\jelix\lib\jelix\dao\jDaoProperty.class.php	156
	/jelix/actu.org/www/index.php/news/news
array (   'module' => 'news',   'action' => 'news:index', )

	0	jDaoProperty->__construct()	C:\wamp\www\jelix\lib\jelix\dao\jDaoParser.class.php : 196
	1	jDaoParser->parseRecord()	C:\wamp\www\jelix\lib\jelix\dao\jDaoParser.class.php : 104
	2	jDaoParser->parse()	C:\wamp\www\jelix\lib\jelix\dao\jDaoCompiler.class.php : 51
	3	jDaoCompiler->compile()	C:\wamp\www\jelix\lib\jelix\core\jIncluder.class.php : 113
	4	jIncluder::inc()	C:\wamp\www\jelix\lib\jelix\dao\jDao.class.php : 39
	5	jDao::create()	C:\wamp\www\jelix\lib\jelix\dao\jDao.class.php : 62
	6	jDao::get()	C:\wamp\www\jelix\lib\jelix\controllers\jControllerDaoCrud.class.php : 181
	7	jControllerDaoCrud->index()	C:\wamp\www\jelix\lib\jelix\core\jCoordinator.class.php : 225
	8	jCoordinator->process()	C:\wamp\www\jelix\actu.org\www\index.php : 19


2017-02-07 16:43:11	::1	notice	2017-02-07 16:43:11	::1	[8]	
Undefined offset: 6	C:\wamp\www\jelix\lib\jelix\dao\jDaoProperty.class.php	158
	/jelix/actu.org/www/index.php/news/news
array (   'module' => 'news',   'action' => 'news:index', )

	0	jDaoProperty->__construct()	C:\wamp\www\jelix\lib\jelix\dao\jDaoParser.class.php : 196
	1	jDaoParser->parseRecord()	C:\wamp\www\jelix\lib\jelix\dao\jDaoParser.class.php : 104
	2	jDaoParser->parse()	C:\wamp\www\jelix\lib\jelix\dao\jDaoCompiler.class.php : 51
	3	jDaoCompiler->compile()	C:\wamp\www\jelix\lib\jelix\core\jIncluder.class.php : 113
	4	jIncluder::inc()	C:\wamp\www\jelix\lib\jelix\dao\jDao.class.php : 39
	5	jDao::create()	C:\wamp\www\jelix\lib\jelix\dao\jDao.class.php : 62
	6	jDao::get()	C:\wamp\www\jelix\lib\jelix\controllers\jControllerDaoCrud.class.php : 181
	7	jControllerDaoCrud->index()	C:\wamp\www\jelix\lib\jelix\core\jCoordinator.class.php : 225
	8	jCoordinator->process()	C:\wamp\www\jelix\actu.org\www\index.php : 19

```

**Comment by laurentj** [comment]
Je vois. En fait il manque le tableau de correspondance de type dans sqlsrv.dbtools.php (champs $typeInfo de la classe sqlsrvDbTools). Il est important car il permet de prendre correctement en compte les valeurs que l'on donne aux DAOs, et de générer correctement les requêtes.

Il faudrait donc l'ajouter, comme cela est fait pour les autres drivers. Par exemple pour Postgresql : https://github.com/jelix/jelix/blob/jelix-1.6.x/lib/jelix/plugins/db/pgsql/pgsql.dbtools.php#L24

Il faut donc se plonger dans la doc de SQLServer pour remplir un tel tableau... Comme je ne connais pas bien SQLServer, et que je n'ai pas trop le temps aujourd'hui, si tu as du temps...

Petites explications :

- les clés = liste de tous les types possibles dans toutes les bases existantes. Si il y a un type dans SQLServer qui est inexistant dans les tableaux des autres drivers, il faudra l'ajouter dans ces autres tableaux

Ensuite, les valeurs sont des tableaux qui contiennent :

- le type qui correspond dans SQLServer
- le type qui correspond parmi les types "unifiés" de jDao. sorte de types qui regroupent plusieurs types similaires, et qui simplifient le code dans jDao. La liste est [là](https://github.com/jelix/jelix/blob/jelix-1.6.x/lib/jelix/db/jDbTools.class.php#L124) 
- valeurs minimum et maximum pour les champs de type numériques (null pour les autres types)
- longueurs minimum et maximum pour les champs de type chaine (null pour les autres types)

**Comment by maelBL** [comment]
Je comprends. En effet certaines propriétés sont mal attribuées, notamment les tailles de champs. Pour les `datatypes ` ça a l’air d'aller mais sans avoir tout testé donc avec potentiellement des erreurs. Je n'ai malheureusement pas le temps ces jours mais je vais regarder ça dès que j'ai un moment !

**Comment by laurentj** [comment]
J'ai ajouté les définitions de type. ça devrait mieux fonctionner maintenant :)

**Comment by maelBL** [comment]
Extra, plus aucun message ne s'affiche maintenant durant la création des DAO, ça fonctionne bien :+1: 

J'ai remarqué deux choses cependant encore :

1. Les longueurs de champ (maxlength) ne sont pas déterminés correctement pour les nvarchar. Toutes les valeurs sont doublées par rapport à la valeur en base.
2. Le findBy($conditions, $offset, $number) ne prends pas en compte le $offset et le $number. Pourtant la fonction est définie suite à [ce ticket de 2010](http://developer.jelix.org/ticket/1160).
