### ISSUE TITLE
jResponseHtmlFragment: problem with gzip compressed response and content length

### ISSUE THREAD

**Issue by julieni** [jelix/jelix#289]
```php
final public function output(){
    //....
    $this->_httpHeaders['Content-length']=strlen($content);
    //....
}
```
The Content-length (should be Content-Length btw) header specifies wrong size when the content is gzip compressed by the server, causing a 5 or more seconds delay before request's "content download" part's end.

A quick fix is to remove the header (as we do not specify it in html response either).

Longer fix will mean detecting if both the server and client can use gzip, and then specify the content size based on compression availability.

**Comment by laurentj** [comment]
> specify the content size based on compression availability.

you mean, set the header only when there is no gzip compression, right?

**Comment by julieni** [comment]
hum, not sure it's even possible, as gzip compression may be added after (proxy, cache, cdn, ...) jelix processed and sent the response I think.
Theses components (proxies, ...) should then rewrite the Content-Length header, but they seem to not do so.
The best approach seems to simply remove the header in all cases, as in the html response.

**Comment by julieni** [comment]
another way may be outputting gzip encoded responses when both client and server support it. Gzip encoded content will not be compressed again.

**Comment by julieni** [comment]
take a look at this simple example. The script reads and outputs it's own source code.

http://issler.net/jelix-gzip-demo.php <- delay (firefox displays quickly but request is not finished, chrome waits before displaying)

http://issler.net/jelix-gzip-demo.php?noheader=1 <- no delay
