### ISSUE TITLE
Wrong argument of chmod() in jIniFile.class.php line 62 (Jelix 1.6)

### ISSUE THREAD

**Issue by Erika31** [jelix/jelix#293]
Jelix 1.6 : needs to replace chmod($f, $chmod) by chmod($filename,$chmod) in /lib/jelix/utils/jIniFile.class.php on line 62
Jelix 1.7 : needs to replace chmod($f, $chmod) by chmod($filename,$chmod) in /lib/vendor/jelix/inifile/lib/Util.php on line 111

**Comment by julieni** [comment]
Thanks Erika31, made PR for both branches

PR #294 for 1.6.x

**Comment by laurentj** [comment]
Thanks @Erika31 for the report, and @julieni for the patch :-)
