### ISSUE TITLE
jForms with passwords input shows password in error log when encountering crashes

### ISSUE THREAD

**Issue by maelBL** [jelix/jelix#297]
I'm using a jForm to allow users to connect to the application. It works really well when there are no critical errors, but otherwise it prints the password both in the debugbar and in the error logs of the application, in blank ! I do use a <secret> tag. For example, when a PHP driver is missing (let's say pdo_sqlsrv), it creates a critical error when trying to get datas from the SQL server database, thus printing the password in blank.

I must keep the password in blank to authenticate with an Active Directory server (ldap), so I can't crypt it as soon as I get the jForm in my controller..

Should I not use a jForm for the login screen ? Is it a bug ?

**Comment by laurentj** [comment]
Sorry, I don't understand what you mean by "blank" password.

Could you explain what you do exactly? Which error log do you talk about? an error coming from where?

**Comment by maelBL** [comment]
Yeah, I thought "blank" would be confusing ^^' I mean that we can see the passwords in the logs, they aren't crypted or anything, just printed like the user wrote them. ("en clair").

I use my own authentification module, based on the Jelix authentification module (jauth). Instead of using a simple form written by hand (https://github.com/jelix/jelix/blob/jelix-1.6.x/lib/jelix-modules/jauth/templates/login.form.tpl), I use a jForm.

Now, when there is a critical error occurring while trying to log in (like an SQL error or anything else) and the log in process is not finished yet, there is a log that is created in the app/var/logs folder. This log contains the description of the error (like a failed SQL query) and also the content of the jForm (which includes the password !).

I guess the problem here is not really where the error come from, it's more that the jForm actually prints the password in the log (even when using a <secret> tag).

**Comment by laurentj** [comment]
Well, I don't see how each Jelix components can deal with it.

>it's more that the jForm actually prints the password in the log 

No, jForms does not log nothing, as it does not execute SQL queries or other. jForms just fetch data from your form, and give them to you.  Your problem is not related to jForms specifically. 

You would have the same problem with any other library not provided by Jelix, as, most of time, a library cannot guess that you give some sensitive content to it.

For example, how could jDb guess that you give it some sensitive data? It cannot. Its role is just to execute SQL queries.

So, IMHO, it's the responsability of your authentication module (which is the only one component that know, in this case, what are the sensitive data), to avoid to leak passwords in logs etc. It can for example catch exceptions, and throw other with less informations or sensitive datas..

**Comment by maelBL** [comment]
I see. I have enabled the error file logging in the mainconfig file, so that's why there is an error log that is created when encountering an error.

You're right, I should catch those exceptions to prevent the log of errors. Thank you for you answers !

**Comment by laurentj** [comment]
I would like to know how the password can be in the log. If there is an SQL problem, the query is logged, this is normal. But if the password appear in this query, then it means you compare a field with the password ? What is your SQL query ? (I suspect you have a security issue here, related with your query)

**Comment by maelBL** [comment]
Here's an example of the log:

> 2017-06-23 14:23:27	::1	notice	2017-06-23 14:23:27	::1	[8]	Undefined property: loginCtrl::$param	C:\wamp\www\jelix\app\modules\pauth\controllers\login.classic.php	36
	/app/index.php/pauth/login/in
array (   'module' => 'pauth',   'action' => 'login:in',   '__JFORMS_TOKEN__' => 'c2fc239a6ff405c744565fd68cdcc959',   'login' => 'my_user_name',   'password' => 'my_password',   '_submit' => 'Se connecter', )

As you can see, this isn't only related to SQL errors. To reassure you, I do not store password, I use them to authenticate with LDAP (and it needs the passwords not crypted...).

**Comment by laurentj** [comment]
Ok, this is not related to jForms (again :-)). Here Jelix just shows all request parameters. So, jForms or not, you would see the same thing (except the jforms token...).

Probably we should have a way to indicate to Jelix that it should not log a specific parameter for a specific action...

**Comment by laurentj** [comment]
A temporary solution is to suppress request parameters from error messages. You can change the [format of error messages](https://docs.jelix.org/fr/manuel-1.6/errormanager] by setting the messageLogFormat parameter in your mainconfig.ini.php or localconfig.ini.php

```
[error_handling]
messageLogFormat = "%date%\t%ip%\t[%code%]\t%msg%\t%file%\t%line%\n\t%url%\n%params%\n%trace%\n\n"
errorMessage="A technical error has occured (code: %code%). Sorry for this inconvenience."
```

remove the `%params%` tag from messageLogFormat.

**Comment by maelBL** [comment]
Thank you for this temporary solution ! Yeah, being able to not log specifics parameters would be great, <secret> jForms tags for example if possible ^^

**Comment by laurentj** [comment]
I'm on a patch ;-)

**Comment by maelBL** [comment]
Awesome, thank you ! :D

**Comment by laurentj** [comment]
A mecanism is now implemented. [Here is the doc in french](https://github.com/jelix/jelix-manuel-fr/blob/jelix-1.6/errormanager.gtw#L49) (english coming soon)
