### ISSUE TITLE
Issue with jacl2db plugin

### ISSUE THREAD

**Issue by laurentj** [jelix/jelix#314]
In some installation, the jacl2db module is recognized as "uninstalled" and then there is an error with the activation of  jacl2db plugin.

A fresh install resolves the issue. But we should investigate why there is this error.

See https://github.com/3liz/lizmap-web-client/issues/724, https://github.com/3liz/lizmap-web-client/issues/720, https://github.com/3liz/lizmap-web-client/issues/689

**Comment by josemvm** [comment]
hi @laurentj 

my last post in https://github.com/3liz/lizmap-web-client/issues/689

the error

`2017-12-12 17:04:33 [130] Module "lizmap" is unknown or disabled /var/www/html/lizmap-web-client-master-edition-32/lib/jelix/core/jCoordinator.class.php 160`

comes from e.g. this command:

`php lizmap/scripts/script.php lizmap~wmts:capabilities montpellier montpellier`

> A fresh install resolves the issue

no, this error appear after a fresh installation!

thanks

**Comment by laurentj** [comment]
Except a bad configuration about the lizmap module enabling (see issue 3liz/lizmap-web-client#689) , I cannot reproduce errors about the jacl2db plugin and I don't see why there was this error.

**Comment by josemvm** [comment]
tested with a fresh installation and without changes

`php lizmap/scripts/script.php lizmap~wmts:capabilities montpellier montpellier`

no errors and no output!...

**Comment by josemvm** [comment]
sorry @laurentj 

in fact, it works!

**Comment by Spitfiire** [comment]
Hi,

same errors, tested on master, php 5.6, fresh installation, windows server 2012
 
`php lizmap/scripts/script.php lizmap~wmts:capabilities montpellier montpellier `

```
 Error during initialization: \n* Error in main configuration on pluginsPath -- Path given in pluginsPath for the module jacl2db is ignored, since this module is unknown or deactivated (C:\my\path\master\lib\jelix\core\jConfigCompiler.class.php 427)
 * Error in the main configuration. A plugin doesn't exist -- The coord plugin jacl2 is unknown. (C:\my\path\master\lib\jelix\core\jConfigCompiler.class.php 168)
```

thanks

**Comment by josemvm** [comment]
on linux/ubuntu, everything works fine!

**Comment by Abelon38** [comment]
Hi ! I am having the sam issue! Using QGIS server 2.18, Lizmap 3.2. Totally new installation and getting this error:
C:\QGISserver\lizmap33>php lizmap/scripts/script.php lizmap~wmts:capabilities inventering stockholm
Error during initialization: \n* Error in main configuration on pluginsPath -- Path given in pluginsPath for the module jacl2db is ignored, since this module is unknown or deactivated (C:\QGISserver\lizmap33\lib\jelix\core\jConfigCompiler.class.php 431)
* Error in the main configuration. A plugin doesn't exist -- The coord plugin jacl2 is unknown. (C:\QGISserver\lizmap33\lib\jelix\core\jConfigCompiler.class.php 172)

**Comment by laurentj** [comment]
@Abelon38 thanks for the report.

However I cannot reproduce the issue. I need more informations :

- which operating system, which version of the operating system
- list of steps you did from the installation of  lizmap sources to the launch of installer.php

Please open a new issue, as this one was closed long time ago, and probably your issue has not the same origin

**Comment by fabianm536** [comment]
Same problem:

Windows Server 2008 R2 SP1 64bits
Apache 2.4.38
php 5.6.40
lizmap- 3.1.12

```
D:\webserver\lizmap\prod\lizmap-web-client-3.1.12>php lizmap/scripts/script.php
lizmap~wmts:capabilities montpellier montpellier
```

> Error during initialization: \n* Error in main configuration on pluginsPath -- P
> ath given in pluginsPath for the module jacl2db is ignored, since this module is
>  unknown or deactivated (D:\webserver\lizmap\prod\lizmap-web-client-3.1.12\lib\j
> elix\core\jConfigCompiler.class.php 427)
> * Error in the main configuration. A plugin doesn't exist -- The coord plugin ja
> cl2 is unknown. (D:\webserver\lizmap\prod\lizmap-web-client-3.1.12\lib\jelix\cor
> e\jConfigCompiler.class.php 168)


However install was ok:

` D:\webserver\lizmap\prod\lizmap-web-client-3.1.12>php lizmap/install/installer.php`
> Installation start..
> [notice] Installation starts for the entry point index
> All modules dependencies are ok
> Module jelix installed
> Module jacl2 installed
> Module jacl2db installed
> Module jacl2db_admin installed
> Module jauthdb_admin installed
> Module master_admin installed
> Module jauth installed
> Module jauthdb installed
> Module admin installed
> Module lizmap installed
> Module proj4php installed
> Module view installed
> All modules are installed or upgraded for the entry point index
> [notice] Installation starts for the entry point admin
> All modules dependencies are ok
> Module jelix installed
> Module jacl2 installed
> Module jacl2db installed
> Module jacl2db_admin installed
> Module jauthdb_admin installed
> Module master_admin installed
> Module jauth installed
> Module jauthdb installed
> Module admin installed
> Module lizmap installed
> Module proj4php installed
> Module view installed
> All modules are installed or upgraded for the entry point admin
> [notice] Installation starts for the entry point script
> All modules dependencies are ok
> Module jelix installed
> Module jacl2 installed
> Module jacl2db installed
> Module jacl2db_admin installed
> Module jauthdb_admin installed
> Module master_admin installed
> Module jauth installed
> Module jauthdb installed
> Module admin installed
> Module lizmap installed
> Module proj4php installed
> Module view installed
> All modules are installed or upgraded for the entry point script
> Installation ended.
