### ISSUE TITLE
jFormsJQControlGroup: subcontrols activation/desactivation

### ISSUE THREAD

**Issue by c-sk** [jelix/jelix#334]
When a control (like `jFormsJQControlDate`) implements the function `deactivate` in Javascript, it seems the function `jFormsJQControlGroup.showActivate()` doesn't enable or disable correctly the control.

https://github.com/jelix/jelix/blob/58454e381e29d3e0ba12ec3dc17696a869206ff3/lib/jelix-www/js/jforms_jquery.js#L1121

The value of `toactivate` comes from `checkboxItem.checked` at a bit higher in the code. When `checkboxItem` is checked, we need to activate the controls in the group. So `toactive` contains `true`.

However, passing `true` directly to `ctl.deactivate()` would disable it. Should we reverse the value instead?

`ctl.deactivate(!toactivate);`

**Comment by laurentj** [comment]
Yes, I think you're right :)

**Comment by laurentj** [comment]
It is fixed. Thanks for your report
