### ISSUE TITLE
No way to recover from "MySQL server has gone away".

### ISSUE THREAD

**Issue by qix67** [jelix/jelix#339]
I currently try to make a very simple script performing the followings tasks:

1. Do a request using a jDao call

1. Perform several computations not requiring SQL connection (jDao or jDb)

1. Performing a new request (select or update) using a call.
	
I have the following settings:
* My MySQL server is configured to drop inactive connections after 5 seconds.
* in php.ini, mysqli.reconnect is set to false to avoid any problem with transaction.

If task 2 runs for more than 5 seconds, when I try to perform task 3, I receive an exception with message "MySQL server has gone away" and from my point of view, I think it is totally normal.

My problem is I see absolutely no way to perform any new SQL query after this exception.

I tried various things after catching exception:

1. Restart the same dao call => trigger the exception a second time

1. Perform a jDb::getConnection() and make a "select 1" query => trigger the exception a second time

1. Perform a jDb::getConnection() and call close() method => no result. The next query does not create a new connection and the same exception is triggered a second time

1. call jDb::testProfile() to try to bring a new connection alive => still no result

1. manually opening a new connection using mysqli_connect => the new connection is created and works but jelix does not use it.

I think I checked the whole jDb/jDao API and no solution seems to exist to recover from this state.

Is it a jelix limit or did I missed something ?

_(By the way, isn't jDb::testProfile() missing a "static" keyword in its declaration in jelix 1.7.x at least ?)_

**Comment by laurentj** [comment]
Hi,

Call `jProfiles::clear()` before executing step 3. I think it will work.

**Comment by qix67** [comment]
Hi,

jProfiles::clear() fixed my problem even without calling close().

However, problem is fixed for all future jDao instances. Already existing ones must be recreated using jDao::get() but it is enough for my case.

Thanks.
