### ISSUE TITLE
[Security] Open Redirect of 'auth_url_return'

### ISSUE THREAD

**Issue by hessandrew** [jelix/jelix#348]
Hello everyone,

I have not seen an option to restrict the redirect of 'auth_url_return' to trusted domains. So it would correspond to the vulnerability CWE-601 ('Open Redirect').

Source: https://cwe.mitre.org/data/definitions/601.html

Examples:

https://demo.lizmap.com/lizmap/admin.php/auth/login/out?auth_url_return=https%3A%2F%2Fsites.google.com%2Fview%2Fnoicer
https://demo.lizmap.com/lizmap/admin.php/auth/login/?auth_url_return=https:%2F%2Fsites.google.com%2Fview%2Fnoicer

Greetings,
any1

**Comment by laurentj** [comment]
Thank you for your report. I will fix that ASAP.
