### ISSUE TITLE
Jelix 1.7 - jMailer SMTP config office365 Problème + Solution Mais quelque chose me semble mal documenté dans la doc

### ISSUE THREAD

**Issue by overghost-sv-007** [jelix/jelix#376]
Bonjour à tous,
j'ai un peu tourné en rond dans la documentation de Jelix.
Mon problème : 
j'ai voulu envoyer un email en utilisant jMailer et le protocole SMTP avec office365.

J'ai donc modifié mon profiles.ini.php comme suit:
```
[smtp:mailer]
smtpHost="smtp.office365.com"
smtpPort=587
; "", "ssl" or"tls"
smtpSecure=tls
helo=
smtpAuth=on
smtpUsername="XXXXXXXXXXXXXXXXXX"
smtpPassword="XXXXXXXXXXXXXXXXXX"
timeout=10
```

Et ce tel que c'est décrit dans la documentation officielle https://docs.jelix.org/en/manual/class-utilities/jmailer partie Paramétrage de base

(Sachez que ça ne marche pas)

J'ai également modifié mon mainconfig.ini.php comme suit :

```
[mailer]
webmasterEmail=""
webmasterName=""

; How to send mail : "mail" (mail()), "sendmail" (call sendmail), "smtp" (send directly to a smtp)
;                   or "file" (store the mail into a file, in filesDir directory)
mailerType = smtp
; Sets the hostname to use in Message-Id and Received headers
; and as default HELO string. If empty, the value returned
; by SERVER_NAME is used or 'localhost.localdomain'.
hostname = 
sendmailPath = "/usr/sbin/sendmail"

; if mailer = file, fill the following parameters
; this should be the directory in the var/ directory, where to store mail as files
filesDir = "mails/"

; The profile in profiles.ini.php where all smtp parameters are stored
smtpProfile=mailer
```

(pour ce fichier là c'est bon pas d'erreurs)

Donc après avoir cherché à peu près 24 heures, j'ai finalement décidé de faire un test différent un utilisant finalement les fonctions proposées par la classe originale PHPMailer...

j'ai donc mis le code suivant dans un controleur:

```
$mail = new jMailer();
$mail->SMTPDebug = SMTP::DEBUG_SERVER;
$mail->isSMTP();
$mail->Host = 'smtp.office365.com';
$mail->SMTPAuth = true;
$mail->Port = 587;
$mail->SMTPSecure = 'tls';
$mail->Username = "";
$mail->Password = "";
$mail->setFrom('');
```

J'ai constaté que ça passait et donc j'ai décidé de retourner complètement à la source de mon fichier profiles.ini.php

J'ai effacé tout et j'ai été chercher le code original dans le fichier profiles.ini.php.tpl disponible dans la lib de jelix.

Et là, j'ai simplement complété les éléments proposés par les valeurs souhaitées.

ce qui donne un fichier profiles.ini.php comme suit:
```
[smtp:mailer]
host="smtp.office365.com"
port=587
; "", "ssl" or"tls"
secure_protocol=tls
helo=
auth_enabled=on
username=""
password=""
timeout=10
```

Maintenant, juste pour savoir, qu'ai-je fait mal pourquoi l'utilisation de la config proposée dans la doc ne fonctionne pas?

Pour l'envoi par SMTP :

```
    smtpHost : le nom du serveur smtp
    smtpPort : le port SMTP
    smtpSecure : connection sécurisée ou pas (valeurs possibles: "", "ssl", "tls")
    smtpHelo : le message HELO de SMTP
    smtpAuth : on/off. Active ou non l'authentification SMTP
    smtpUsername : le login pour se connecter sur le serveur
    smtpPassword : le mot de passe pour se connecter sur le serveur
    smtpTimeout : la durée maximale de tentative de connection au serveur SMTP.
```

Est-ce que cette partie dans la doc ne serait pas correctement documentée? je ne la comprends pas bien....

Merci pour l'aide/l'éclaircissement.

J'espère que ceci aidera d'autres développeurs qui seraient confrontés au même soucis que moi.

**Comment by laurentj** [comment]
Bonjour,

La documentation pourrait effectivement être un peu plus claire.

En fait, vous avez confondu entre deux manières de configurer.

Il y a la première manière, qui indique de mettre, dans la section `[mailer]` du fichier `localconfig.ini.php`,  les paramètres `smtpHost`, `smtpPort` etc. Cette section contient tout et il n'y a rien dans profiles.ini.php.

Il y a la deuxième manière de faire, qui est de mettre tous les paramètres smtp (`host`, `port` etc) dans un profile `[smtp:my_mailer]` dans le fichier `profiles.ini.php`, et d'indiquer ce nom de profile dans la section `[mailer]` du fichier `localconfig.ini.php`.

Votre erreur a été de mettre les paramètres de la première manière de faire, dans un profile comme dans la deuxième manière de faire, ce qui ne fonctionne pas...

Mais je vous l'accorde, la distinction entre les deux manières de faire n'est pas claire dans la doc, je vais arranger ça.

Pour info, la première façon de faire est historique, mais dépréciée, dans la mesure où il a été préféré ensuite de rassembler dans un même fichier, profiles.ini.php, toutes les informations d'accés (login, mot de passe etc) aux différents services (smtp, bases de données etc).

**Comment by laurentj** [comment]
Doc améliorée 

- https://docs.jelix.org/en/manual/class-utilities/jmailer
- https://docs.jelix.org/fr/manuel/classes-utiles/jmailer

**Comment by laurentj** [comment]
Merci pour ce retour

**Comment by overghost-sv-007** [comment]
Super,
merci en effet là c'est beaucoup plus clair :)
toute bonne journée à vous!
