### ISSUE TITLE
Use of jForms in Jelix 1.6.37 opt version results in PHP fatal error

### ISSUE THREAD

**Issue by zl4yy** [jelix/jelix#380]
Hi,

Updating an existing Jelix website from 1.6.31 to 1.6.37 leads to fatal PHP error when using jForms.
At line 537 in ./jelix/forms/jFormsControl.class.php, the code require_once(__DIR__.'/jFormsControlUpload2.class.php');
must be removed (entire line removed) as the php file called does not exist.
The code in the dev version is different therefore does not raise errors.

Regards,
Yan.

**Comment by laurentj** [comment]
Hi,

Sorry, the file `jFormsControlUpload2.class.php` was missing from the package. 

Thank you for your report.

**Comment by laurentj** [comment]
I will release a new version probably this week. You can copy the file into your `lib/jelix/forms/controls/jFormsControlUpload2.class.php` directly from [the repository](https://raw.githubusercontent.com/jelix/jelix/jelix-1.6.x/lib/jelix/forms/controls/jFormsControlUpload2.class.php)

**Comment by zl4yy** [comment]
Bonjour Laurent,

Merci d'avoir réglé le problème. Je vais télécharger la nouvelle version plus tard ce weekend.
Il y a aussi une régression au niveau du formatage des jForms. Le contenu du <label> sortant au mauvais endroit. Le workaround que j'ai trouvé c'est de mettre tous mes fields dans un groupe, et là ça marche. Les <choice> que j'utilise beaucoup ne sont pas affectés par le problème. Je voulais créer un ticket mais j'ai était un peu pris par le travail...

Cordialement,
Yannick.
---
Yannick Devos - ZL4YY
https://www.qscope.org/
