### ISSUE TITLE
Mailer: set SMTPAutoTLS=false

### ISSUE THREAD

**Issue by u-cav** [jelix/jelix#384]
As described here:

https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#opportunistic-tls

PHPMailer 5.2.10 introduced opportunistic TLS, which could cause issues if the server is advertising TLS with an invalid certificate (for example, a self signed one).
I am not finding a way to set this variable in the Jelix mailer. Is that the case, or am I missing something?
Thanks!

**Comment by laurentj** [comment]
I implemented a new value for `secure_protocol`: `uncrypted`, which set `SMTPAutoTLS` to false and `SMTPSecure` to an empty value

**Comment by laurentj** [comment]
Thanks for your report.

**Comment by u-cav** [comment]
@laurentj Thank you for the implementation
