### ISSUE TITLE
Jelix 1.7.8 Créer une interface d'administration

### ISSUE THREAD

**Issue by overghost** [jelix/jelix#392]
Bonjour,
dans la documentation de jelix 1.7.8, on peut lire qu'on peut créer une interface d'administration via la commande suivante:
php dev.php app:init-admin index
Malheureusement, cela me retourne l'erreur suivante:

In IniModifier.php line 355:
                                                                                             
  Impossible to write into projet/var/config/index/auth.coord.ini.php  
                                                                                             

app:init-admin [--profile PROFILE] [--no-jauthdb] [--no-jauth] [--no-jauthdb-admin] [--install-jpref-admin] [--no-acl2db] [--] <entrypoint>

Ceci vient selon moi du fait que le fichier de configuration visé se trouve maintenant dans projet/app/system/index/...

Cela est-il possible?

d'autres personnes ont-elles été confrontées au même problème?

j'ai configuré mon accès à la db en préalable évidemment.
Merci pour le suivi

**Comment by laurentj** [comment]
Merci pour ce rapport de bug. Il est corrigé dans la version 1.7.14 qui va sortir cette semaine.
