### ISSUE TITLE
Modification du tag <html>

### ISSUE THREAD

**Issue by overghost** [jelix/jelix#398]
Bonjour,
existe-t-il une méthode permettant d'ajouter une class sur le tag <html>? (je n'en ai pas trouvé du coup j'ai bidouillé le code source)

si non, j'ai bidouillé moi même un truc, qui fonctionne, mais j'imagine qu'il y aurait mieux à faire...
(j'ai besoin de pouvoir ajouter une class dans le cadre d'un template que j'essaie d'intégrer)

voici ce que j'ai fait:
fichier modifié : 
vendor\vendor\jelix\jelix\lib\jelix\core\response\jResponseHtml.class.php

ajout d'une variable permettant de stocker la valeur souhaitée:
`/**
     * Html TAG Class of the document.
     *
     * @var string
     */
    public $svhtmlcss = '';`

Ajout d'une méthode pour définir la valeur de la variable:
`/**
     * set the class of the html tag of the page.
     *
     * @param string $title
     */
    public function setSvHtmlcss($svhtmlcss)
    {
        $this->svhtmlcss = $svhtmlcss;
    }`

Modification de la fonction qui output le contenu du tag html:
`/**
     * generate the doctype. You can override it if you want to have your own doctype, like XHTML+MATHML.
     *
     * @since 1.1
     */
    protected function outputDoctype()
    {
        echo '<!DOCTYPE HTML>', "\n";
        $locale = str_replace('_', '-', $this->_locale);
        if ($this->_isXhtml) {
            echo '<html class="'.htmlspecialchars($this->svhtmlcss).'" xmlns="http://www.w3.org/1999/xhtml" xml:lang="',$locale,'" lang="',$locale,'">'."\n";
        } else {
            echo '<html class="'.htmlspecialchars($this->svhtmlcss).'" lang="',$locale,'">'."\n";
        }
    }`

Serait-ce envisageable d'intégrer ce genre de possibilités pour le futur?
merci

**Comment by laurentj** [comment]
Bonjour,

Il y a une méthode [setBodyAttributes()](https://jelix.org/reference/1.8/classes/jResponseHtml.html#method_setBodyAttributes): `$response->setBodyAttributes(array('class'=>'myclass'))`

**Comment by overghost** [comment]
Hmm... ok toutefois, tel que je viens de tester cette méthode et tel que je comprends son fonctionnement, la classe sera append au tag <body>.
Ici je cherche vraiment à appliquer cette classe au tag html...
(pour mieux comprendre, dans la doc technique du template que j'utilise, il y a l'information suivante:
(la doc complète peut être retrouvée ici https://prium.github.io/phoenix/v1.13.0/documentation/layouts/combo-navbar.html)

```
Navbar combo structure

Add .navbar-combo class in Html element to start with horizontal-navbar

<!DOCTYPE html>
<html class="navbar-combo">

  <head>...</head>

  <body>
    <main>
      <div class="container-fluid">
        <nav class="navbar navbar-vertical navbar-expand-lg">
          <!-- navbar vertical content goes here-->
        </nav>
        <nav class="navbar navbar-top navbar-expand">
          <!-- navbar top content goes here-->
        </nav>
        <div class="content">
          <!--  content goes here-->
        </div>
      </div>
    </main>
  </body>

</html>


```

Donc je pense que la solution que tu proposes n'est pas suffisante dans mon cas. Et sauf si je me trompe, il n'y a actuellement aucune possibilité de modifier le tag <html> directement si?

**Comment by laurentj** [comment]
Pardon, j'ai confondu `<body>` et `<html>`. En l'état, non il n'est pas possible d'ajouter un attribut sur `<html>` facilement.  Une solution est de créer un objet réponse qui hérite de `jReponseHtml`, redéfini la méthode `outputDoctype()` (c'est elle qui génère le tag `html`), et propose une méthode pour changer la classe au niveau de `<html>`.

**Comment by laurentj** [comment]
J'ai fait la modification pour la prochaine version de maintenance de Jelix 1.8  : [2b5cfd8](https://github.com/jelix/jelix/commit/2b5cfd8cefc645fc2deb29081fb54beb0e26e2a3)
