### ISSUE TITLE
jDao Erreur lors de la création d'un DAO

### ISSUE THREAD

**Issue by xylle** [jelix/jelix#400]
Bonjour,

j'ai rencontré une erreur lors de la création d'un DAO sur une base de données mariadb.
Si un champs a une valeur par défaut null, il y a une erreur. Si j’enlève la contrainte, l'erreur disparaît.
Commande : `php dev.php module:create-dao test utilisateurs1 utilisateurs`

Erreur : [Erreur_Jelix.txt](https://github.com/jelix/jelix/files/12568257/Erreur_Jelix.txt)

Requête SQL de la table : 
```
CREATE TABLE `utilisateurs` (
  `utilisateur_id` int(11) NOT NULL,
  `courriel` varchar(255) NOT NULL,
  `nom` varchar(255) DEFAULT '_',
  `prenom` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
```
Version :

- jelix : 1.8.2
- php : 8.2.10
- OS : Debian 11
- MariaDB : 10.5.19-MariaDB-0+deb11u2

**Comment by laurentj** [comment]
Bonjour, l'erreur est corrigé dans la prochaine version de Jelix 1.7 et 1.8.

Pour avoir la correction tout de suite, utiliser la version "dev-jelix-1.8.x" si c'est installé avec Composer, ou [cette archive](https://download.jelix.org/jelix/nightly/1.8.x/jelix-1.8.3-pre.zip).
