### ISSUE TITLE
[Question] Return value of INSERT prepared statement in pgsql.dbresultset.php

### ISSUE THREAD

**Issue by mind84** [jelix/jelix#402]
Hi @laurentj!

How can I get the result of an INSERT prepared statement?

For example, for PostgreSQL the method `execute()` in the class `pgsql.dbresultset.php` (https://jelix.org/reference/1.7/files/lib-jelix-plugins-db-pgsql-pgsql-dbresultset.html) returns `true` every time and stores the `pg_execute()` result in a class variable (`$this->_idResult`) which is not exposed.

I can't find a solid way to determine whether an INSERT statement was successful or not, do you have any suggestions?

On the other hand, maybe could be usefult to expose a public method to get the the `_idResult` value  (e.g. $stmt->getIdResult()). According to the php documentation the result should be `false` if errors occur or a `PgSql\Result` instance if successful.

Thanks!

**Comment by mind84** [comment]
Nevemind,

I think that `jDbResultSet -> id()`  method are already doing the job.

Sorry for the noise.

Thanks

**Comment by laurentj** [comment]
Hi,

I [fixed two weeks ago](https://github.com/jelix/jelix/commit/da689f1ed905bb24639d501fd289a17cad120494) this issue. This is available into Jelix 1.8.9.

Now the `execute()` return true or false, depending of the result of `pg_execute()`.
